### PR TITLE
Handle cache download errors

### LINKED ISSUE #252: Fails to update cache: thread 'main' panicked (Arch Linux)
When I run `RUST_BACKTRACE=full tldr --update`, this is the error I get:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArchive("Could not find central directory end")', src/cache.rs:166:33
stack backtrace:
0:     0x560e37b784fd - <unknown>
1:     0x560e379d62ec - <unknown>
2:     0x560e37b76d84 - <unknown>
3:     0x560e37b774d0 - <unknown>
4:     0x560e37b7685a - <unknown>
5:     0x560e37b978f8 - <unknown>
6:     0x560e37b97876 - <unknown>
7:     0x560e37b97832 - <unknown>
8:     0x560e37962b60 - <unknown>
9:     0x560e37962e42 - <unknown>
10:     0x560e37bae307 - <unknown>
11:     0x560e37bc3dd5 - <unknown>
12:     0x560e37bb63a3 - <unknown>
13:     0x560e37bbfb79 - <unknown>
14:     0x7f4d4a849b25 - __libc_start_main
15:     0x560e3796d54e - <unknown>
16:                0x0 - <unknown>
```

About my system:
OS: Arch Linux
tealdeer version: 1.5.0

### PR DESCRIPTION
**Pull request by dbrgn**
With this fix, when an invalid ZIP is downloaded:

```
  Error: Could not update cache

  Caused by:
      0: Could not decompress downloaded ZIP archive
      1: invalid Zip archive
```

When a non-successful HTTP error status is returned:

```
  Error: Could not update cache

  Caused by:
      0: Could not download tldr pages from https://tldr.sh/assets/tldr.zap
      1: HTTP status client error (404 Not Found) for url (https://tldr.sh/assets/tldr.zap)
```

Anyhow is awesome 🙂

Fixes #252.

### CODE REVIEW

File: src/cache.rs [hunk 1]
```diff
@@ -150,16 +150,20 @@ impl Cache {
...
         debug!("{} bytes downloaded", bytes_downloaded);
         Ok(buf)
     }
 
     /// Decompress and open the archive
-    fn decompress<R: Read + Seek>(reader: R) -> ZipArchive<R> {
-        ZipArchive::new(reader).unwrap()
+    fn decompress<R: Read + Seek>(reader: R) -> Result<ZipArchive<R>> {
+        Ok(ZipArchive::new(reader)?)
     }
```
Comment (niklasmohrin) [inline src/cache.rs:168]: Is there any benefit from having this as a method now? it would probably be easier to just inline it

File: src/cache.rs [hunk 2]
```diff
@@ -150,16 +150,20 @@ impl Cache {
         let client = builder
             .build()
             .context("Could not instantiate HTTP client")?;
-        let mut resp = client.get(&self.url).send()?;
+        let mut resp = client
+            .get(&self.url)
+            .send()?
```
Comment (niklasmohrin) [inline src/cache.rs:155]: We don't provide any `context` here, but the errors are pretty clear so we can leave it like this :)

Nice find with `error_for_status`!

File: src/cache.rs (hunk 1 above)
Comment (dbrgn) [reply src/cache.rs:168]: Yeah, that's true.

**Review by niklasmohrin — APPROVED** [review]
